# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy React app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # Updated to v2

      - name: Set up Node.js version
        uses: actions/setup-node@v2 # Updated to v2
        with:
          node-version: '14' # Update to your desired Node.js version, e.g., '14' or '16'

      - name: npm install and build
        run: |
          npm ci
          npm run build
        working-directory: .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2 # Updated to v2
        with:
          name: react-app
          path: ./Basketball-Grid-Game/build # Specify the path to the build folder

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2 # Updated to v2
        with:
          name: react-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'YourAzureWebAppName' # Replace with your Azure Web App name
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_APP_SERVICE_PUBLISH_PROFILE }} # Update with your Azure Publish Profile secret
          package: ${{ github.workspace }}/react-app
